dashboard_sc1_by_cm:
    path: /sc1_by_cm/{cm}
    controller: App\Controller\Back\SousCategories1Controller::Souscategories1bycm    
dashboard_sc2_by_sc1:
    path: /sc2_by_sc1/{sc1}
    controller: App\Controller\Back\SousCategories2Controller::Souscategories2bysc1   
test_email:
    path: /test_email
    controller: App\Controller\Front\FrontController::testEmail2
confirmation_account:
    path: /confirmation_account
    controller: App\Controller\Front\FrontController::confirmationAccount
index_page:
    path: /
    controller: App\Controller\Front\FrontController::indexPage

new_pproducts_page:
    path: /new_pproducts
    controller: App\Controller\Front\FrontController::newProductsPage
    
vente_flash:
    path: /vente_flash
    controller: App\Controller\Front\FrontController::venteFlashPage
    
all_stores:
    path: /all_stores
    controller: App\Controller\Front\FrontController::allStoresPage    
    
search_stores:
    path: /search_stores
    controller: App\Controller\Front\FrontController::searchStoresPage     
    
about_page:
    path: /qui_sommes_nous
    controller: App\Controller\Front\FrontController::aboutPage
    
contact_page:
    path: /contact
    controller: App\Controller\Front\FrontController::contactPage
    
contact_send:
    path: /contact_send
    controller: App\Controller\Front\FrontController::contactSend   
    
subscribe_to_news_letter:
    path: /subscribe_to_news_letter
    controller: App\Controller\Front\FrontController::subscribeToNewsLetter     
    
process_order_page:
    path: /passer_une_commande
    controller: App\Controller\Front\FrontController::processOrderPage    
    
product_by_category:
    path: /categorie/{slug}
    controller: App\Controller\Front\FrontController::productByCategory 
    
product_by_store:
    path: /boutique/{slug}
    controller: App\Controller\Front\FrontController::store      
tri_product:
    path: /tri_product
    controller: App\Controller\Front\ProductController::triAction    
    
search_result:
    path: /result
    controller: App\Controller\Front\FrontController::searchResult     
    
product_page:
    path: /product/{slug}
    controller: App\Controller\Front\FrontController::productPage  

livraison_page:
    path: /livraison
    controller: App\Controller\Front\CartController::livraison    
    
slider_front_details:
    path: /offres/{slug}
    controller: App\Controller\Back\SlidersController::showInFront    
    
banner_front_details:
    path: /nouveautes/{slug}
    controller: App\Controller\Back\BannersController::showInFront    
    
new_products:
    path: /new_products
    controller: App\Controller\Front\ProductController::newProducts    
    
products_in_promotion:
    path: /products_in_promotion
    controller: App\Controller\Front\ProductController::productsInPromotion    
dashboard_cmd_filter:
    path:  /filter/commandes
    controller: App\Controller\UserController::filterCommandes
dashboard_cmd_revenu:
    path:  /filter/revenu
    controller: App\Controller\UserController::filterRevenu

dashboard_product_add_remove_liees:
    path: /add_remove_liees
    controller: App\Controller\Back\ProductBackController::addAndRemove

login:
    path:  /connexion
    defaults: { _controller: App\Controller\SecurityController::login }
    