dashboard_list_products_details:
    path: /{id}/details
    controller: App\Controller\Back\ListProductsBackController::details 

dashboard_product_order_in_list:
    path: /product_order_in_list
    controller: App\Controller\Back\ProductBackController::productOrderInList 

dashboard_product_delete_from_list:
    path: /product_delete_from_list/{id}/{product}
    controller: App\Controller\Back\ProductBackController::productDeleteFormList 